'use client';
import { useEffect, useState } from 'react';
import styles from './BillingPanel.module.css';

type Pack={id:string;name:string;description:string;credits:number;amount:number;currency:string;highlighted?:boolean};
type Payment={id:string;pack_id:string;credits:number;amount:number;currency:string;status:string;failure_reason?:string;created_at:string};
function money(amount:number,currency:string){const zero=new Set(['vnd','jpy','krw','clp','pyg','xaf','xof','xpf']);return new Intl.NumberFormat('vi-VN',{style:'currency',currency:currency.toUpperCase()}).format(amount/(zero.has(currency.toLowerCase())?1:100))}
export default function BillingPanel({payments,onError}:{payments:Payment[];onError:(value:string)=>void}){const[packs,setPacks]=useState<Pack[]>([]);const[buying,setBuying]=useState('');
  useEffect(()=>{fetch('/api/billing/catalog',{cache:'no-store'}).then((r)=>r.json()).then((d)=>setPacks(Array.isArray(d.packs)?d.packs:[])).catch(()=>onError('Không tải được bảng giá.'))},[onError]);
  async function buy(packId:string){setBuying(packId);onError('');try{const response=await fetch('/api/billing/checkout',{method:'POST',headers:{'Content-Type':'application/json','x-idempotency-key':crypto.randomUUID()},body:JSON.stringify({packId})});const data=await response.json() as {checkoutUrl?:string;message?:string};if(!response.ok||!data.checkoutUrl)throw new Error(data.message||'Không tạo được thanh toán.');window.location.assign(data.checkoutUrl)}catch(cause){onError(cause instanceof Error?cause.message:'Không thể thanh toán.');setBuying('')}}
  return <><section className={styles.section}><div className={styles.header}><div><span>MUA CREDIT</span><h2>Chọn gói phù hợp</h2></div><small>Stripe Checkout · cộng credit bằng webhook đã xác minh</small></div><div className={styles.packs}>{packs.map((pack)=><article key={pack.id} data-highlighted={pack.highlighted}><strong>{pack.name}</strong><b>{pack.credits} credit</b><p>{pack.description}</p><div>{money(pack.amount,pack.currency)}</div><button disabled={Boolean(buying)} onClick={()=>buy(pack.id)}>{buying===pack.id?'Đang mở thanh toán...':'Mua gói này'}</button></article>)}</div></section><section className={styles.section}><div className={styles.header}><div><span>THANH TOÁN</span><h2>Lịch sử giao dịch</h2></div><small>20 giao dịch gần nhất</small></div><div className={styles.payments}>{payments.length===0?<p>Chưa có giao dịch nào.</p>:payments.map((item)=><article key={item.id}><div><strong>{item.pack_id.toUpperCase()}</strong><small>{item.credits} credit</small></div><b>{money(item.amount,item.currency)}</b><span data-status={item.status}>{item.status}</span><time>{new Date(item.created_at).toLocaleString('vi-VN')}</time>{item.failure_reason?<p>{item.failure_reason}</p>:null}</article>)}</div></section></>}
