'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import BillingPanel from '../../components/account/BillingPanel';
import styles from './page.module.css';

type Payment={id:string;pack_id:string;credits:number;amount:number;currency:string;status:string;failure_reason?:string;created_at:string};
type AccountData={ok:boolean;message?:string;user?:{email:string};profile?:{plan:string;credits:number;credit_debt:number;hourly_scene_limit:number;max_active_scenes:number;video_retention_days:number};generations?:Array<{id:string;status:string;model:string;storage_status:string;error_message?:string;created_at:string}>;outputs?:Array<{id:string;title:string;status:string;aspect_ratio:string;error_message?:string;created_at:string}>;payments?:Payment[]};
export default function AccountPage(){const[data,setData]=useState<AccountData|null>(null);const[error,setError]=useState('');const[notice,setNotice]=useState('');
  const load=useCallback(()=>{fetch('/api/account',{cache:'no-store'}).then(async(r)=>{const d=await r.json() as AccountData;if(!r.ok||!d.ok)throw new Error(d.message||'Không đọc được tài khoản.');setData(d)}).catch((cause)=>setError(cause instanceof Error?cause.message:'Không đọc được tài khoản.'))},[]);
  useEffect(()=>{const params=new URLSearchParams(window.location.search);if(params.get('payment')==='success')setNotice('Thanh toán đã hoàn tất. Credit được cộng sau khi Stripe xác nhận webhook.');if(params.get('payment')==='cancelled')setNotice('Bạn đã hủy thanh toán. Không có credit nào bị thay đổi.');load()},[load]);
  const stats=useMemo(()=>{const rows=data?.generations||[];return{active:rows.filter((r)=>['reserved','submitted','processing'].includes(r.status)).length,completed:rows.filter((r)=>r.status==='succeeded').length}},[data]);
  return <main className={styles.page}><section className={styles.hero}><div><span>TÀI KHOẢN SAAS</span><h1>Credit, thanh toán và kho video</h1><p>{data?.user?.email||'Đang tải...'}</p></div><a href="/">Tạo video mới</a></section>{notice?<div className={styles.notice}>{notice}</div>:null}{error?<div className={styles.error}>{error}</div>:null}<section className={styles.stats}><article><span>Credit còn lại</span><strong>{data?.profile?.credits??'—'}</strong><small>{data?.profile?.credit_debt?`Nợ hoàn tiền: ${data.profile.credit_debt}`:'Mỗi cảnh dùng 1 credit'}</small></article><article><span>Gói hiện tại</span><strong>{data?.profile?.plan?.toUpperCase()||'—'}</strong><small>{data?.profile?.hourly_scene_limit??'—'} cảnh mỗi giờ</small></article><article><span>Đang xử lý</span><strong>{stats.active}</strong><small>Tối đa {data?.profile?.max_active_scenes??'—'} cảnh đồng thời</small></article><article><span>Lưu video</span><strong>{data?.profile?.video_retention_days??'—'} ngày</strong><small>{stats.completed} cảnh hoàn thành gần đây</small></article></section><BillingPanel payments={data?.payments||[]} onError={setError}/><section className={styles.history}><div className={styles.sectionHeader}><h2>Video hoàn chỉnh</h2><span>20 video gần nhất</span></div><div className={styles.list}>{(data?.outputs||[]).length===0?<p className={styles.empty}>Chưa có video hoàn chỉnh.</p>:(data?.outputs||[]).map((item)=><article key={item.id}><div><strong>{item.title}</strong><small>{new Date(item.created_at).toLocaleString('vi-VN')} · {item.aspect_ratio}</small></div><span data-status={item.status}>{item.status}</span>{item.status==='succeeded'?<a href={`/api/outputs/${item.id}/download`}>Tải video</a>:<span/>}{item.error_message?<p>{item.error_message}</p>:null}</article>)}</div></section><section className={styles.history}><div className={styles.sectionHeader}><h2>Job từng cảnh</h2><span>20 cảnh gần nhất</span></div><div className={styles.list}>{(data?.generations||[]).map((item)=><article key={item.id}><div><strong>{item.model}</strong><small>{new Date(item.created_at).toLocaleString('vi-VN')}</small></div><span data-status={item.status}>{item.status}</span><span>{item.storage_status}</span>{item.storage_status==='archived'?<a href={`/api/videos/${item.id}/download`}>Mở cảnh</a>:<span/>}{item.error_message?<p>{item.error_message}</p>:null}</article>)}</div></section></main>}
